spring:
  datasource:
    url: jdbc:postgresql://ep-delicate-forest-a5pp7vcy.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=7rIhoRZuE3cp&sslmode=require
    username: neondb_owner
    password: 7rIhoRZuE3cp
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
